name:                wamphfind
version:             0.1.0.0
github:              "adpextwindong/wamphfind"
license:             BSD2
author:              "George Takumi Crary"
maintainer:          "George Takumi Crary"
copyright:           "2021 George Takumi Crary"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wamphfind#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  wamphfind-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wamphfind

tests:
  wamphfind-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wamphfind
